files:
  - source: /en/**/*.md
    ignore:
      - /_book
      - /node_modules
      - /CONTRIBUTING.md
    translation: /%two_letters_code%/**/%original_file_name%
  - source: /en/*.md
    translation: /%two_letters_code%/%original_file_name%
    ignore:
      - /_book
      - /node_modules
      - /CONTRIBUTING.md
