files:
  -
    source: "/en/**/*.md"
    translation: "/%two_letters_code%/%original_path%/%original_file_name%"
    ignore:
      - /_book
      - /node_modules
      - /CONTRIBUTING.md
  -
    source: "/en/*.md"
    translation: "/%two_letters_code%/%original_file_name%"
    ignore:
      - /_book
      - /node_modules
      - /CONTRIBUTING.md
